server.port=8084
spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# para observabilidad monitoreo
# sin tildes porque por eso causa error en clean
resilience4j.circuitbreaker.instances.productoServiceCB.registerHealthIndicator=true
# es el numero de llamadas maximo que espera para verificar error de comunicacion
resilience4j.circuitbreaker.instances.productoServiceCB.slidingWindowSize=10
# numero minimo de llamadas antes de calcular el error
resilience4j.circuitbreaker.instances.productoServiceCB.minimumNumberOfCalls=5
# umbral de error en porcentaje para abrir el circuito  en este caso mayor o igual 50 por ciento
resilience4j.circuitbreaker.instances.productoServiceCB.failureRateThreshold=50
# tiempo en que el circuito estara abierto en este caso es un minuto
resilience4j.circuitbreaker.instances.productoServiceCB.waitDurationInOpenState=1m
# es el numero de llamadas permitidas cuando el circuito esta medioabierto para verificar si se recupero el circuito
# esto pasa luego del tiempo determinado en waitDurationInOpenState pero requiere que todos los request sean exitosos
# basta que falte uno para no permitir el cierre
resilience4j.circuitbreaker.instances.productoServiceCB.permittedNumberOfCallsInHalfOpenState=3
# esto se apoya en el tiempo de waitDurationInOpenState despues de ese tiempo se medio cierra y permite paso de comprobaciones
resilience4j.circuitbreaker.instances.productoServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true
# tiempo en que se vuelve a abrir si fallan los requests
resilience4j.circuitbreaker.instances.productoServiceCB.maxWaitDurationInHalfOpenState=20s
# tiempo de espera para que el servicio responda en este caso es 3 segundos luego se asume que no responde ni funciona
resilience4j.timelimiter.instances.productoServiceCB.timeoutDuration=3s
